version: '3.8'

services:
  embed-nordic:
    build: .
    image: embed-nordic:latest
    container_name: nordic-embeddings
    ports:
      - "7000:7000"
    environment:
      - MODEL_NAME=${MODEL_NAME:-norbert2}
      - MODEL_PATH=/app/models
      - HOST=0.0.0.0
      - PORT=7000
      - DEVICE=${DEVICE:-cpu}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE:-32}
      - MAX_LENGTH=${MAX_LENGTH:-512}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

